### ISSUE TITLE
154 - Health Network Optimization in Lima

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#148]
The proposal was with Google. The team sent these as results - [https://imagebank2.worldbank.org/Search/31199830](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fimagebank2.worldbank.org.mcas.ms%2FSearch%2F31199830%3FMcasTsid%3D20893&McasCSRF=0c390f2c55da9f101224444648d6a6a7817175f9a4354eb45fd6301c9ab6ca73)

**Comment by claudiacalderon** [comment]
@SahitiSarva changed to data explored
