### ISSUE TITLE
ADVANCED DIGITAL SKILLS PENETRATION IN LATIN AMERICA AND THE CARIBBEAN

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#152]
IADB Project that now has a published [report](https://publications.iadb.org/en/360-digital-transformation-firms-latin-america-and-caribbean)

**Comment by samsonlee530** [comment]
I will work on this one after the Ukraine story.

**Comment by samsonlee530** [comment]
Here is a [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B29096269-B3F9-449C-AE94-FD3CC0CADCAC%7D&file=DRAFT%20224%20Impact%20Story%20Digital%20Transformation%20LAC.docx&action=default&mobileredirect=true&CID=0fed9b63-95ee-b8d7-49cc-c5d4e85534b8)

**Comment by samsonlee530** [comment]
I have sent the draft to IDB.

**Comment by samsonlee530** [comment]
Pull request: https://github.com/datapartnership/datapartnership.github.io/pull/248
