### ISSUE TITLE
264 - Understanding the determinants of vaccine hesitancy across countries

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/datapartnership.github.io#153]
From: Duong Trung Le

<blockquote>

Dear team,

 

I would like to give you an update that the preliminary findings of the proposed project using the dataset Facebook’s Global COVID-19 Trends and Impact Survey was published in the EAP Economic Update April 2022 report:

 

[https://openknowledge.worldbank.org/bitstream/handle/10986/37097/9781464818585.pdf](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fopenknowledge.worldbank.org.mcas.ms%2Fbitstream%2Fhandle%2F10986%2F37097%2F9781464818585.pdf%3FMcasTsid%3D20893&McasCSRF=ddb48f5344fc24969c4143bf908682cf56aedf2a83e09b125362291c13578736)

**Comment by claudiacalderon** [comment]
@samsonlee530 you can work on this one

**Comment by samsonlee530** [comment]
A draft will be ready tomorrow (Jun 13).

**Comment by samsonlee530** [comment]
Final version is [here](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B52CC18B9-EDFA-4ECB-8AF0-39C021E7D84F%7D&file=FINAL%20Impact%20Story%20vaccination%20in%20EAP.docx&action=default&mobileredirect=true)

**Comment by samsonlee530** [comment]
Pull request is [here](https://github.com/datapartnership/datapartnership.github.io/pull/230)
