### ISSUE TITLE
Detecting Urban Clues for Road Safety

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#157]
https://github.com/datapartnership/integrated-framework-for-road-safety

https://documents1.worldbank.org/curated/en/099200002152227482/pdf/P170812026cd2b0550acec0ef8165301833.pdf

The project has been completed for a while and has a GitHub repo associated with it

**Comment by samsonlee530** [comment]
Please see this [draft] (https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/Detecting%20Urban%20Clues%20for%20Road%20Safety/DRAFT%20Impact%20Story%20Detecting%20Urban%20Clues.docx?d=w5d25f32415b742aaa947d763a0638656&csf=1&web=1&e=d1yqly).

**Comment by samsonlee530** [comment]
Sarah edited the draft. We then sent it to Marena from Mapbox. But she wanted to know about the use of the maps. @claudiacalderon Have you replied to her yet? If not, I can tell her that the World Bank didn't use Mapbox data for the final models as Sarah said. Thanks

**Comment by g4brielvs** [comment]
@samsonlee530 finalized the impact story. It's now published.
