### ISSUE TITLE
306 - GREEN JOBS OPPORTUNITIES FOR WOMEN IN THE LATIN AMERICA AND THE CARIBBEAN REGION

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#158]
IDB Project that successfully used LinkedIn data. 

https://publications.iadb.org/en/gender-and-inclusion-green-agenda-where-are-we-and-how-move-forward

**Comment by samsonlee530** [comment]
@claudiacalderon Please see this [draft](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/306%20-%20Green%20jobs%20opportunities%20for%20women%20in%20the%20Latin%20America%20and%20the%20Caribbean%20region/DRAFT%20Impact%20Story%20green%20jobs%20for%20women.docx?d=wcaa8fccff87f495082b1e3277b3ed101&csf=1&web=1&e=AgtTH3)

**Comment by samsonlee530** [comment]
@claudiacalderon @g4brielvs @SahitiSarva Update: The IDB team reviewed the draft and suggested changing our sub-headings (challenge, solution and impact) of the blog post. I replied to them that we would normally not change the titles. But they could suggest new titles if they want.

**Comment by samsonlee530** [comment]
Good news! The IDB team has approved everything. Please see this finalized [version](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/306%20-%20Green%20jobs%20opportunities%20for%20women%20in%20the%20Latin%20America%20and%20the%20Caribbean%20region/FINAL%20Impact%20Story%20green%20jobs%20for%20women_KKL.docx?d=wf85d5525fb584fd08c07bb26d5751cfd&csf=1&web=1&e=MoL9nG)

Please also note that I added a footnote about green jobs (under the challenge section )to the blog post as suggested by the team

**Comment by samsonlee530** [comment]
Here are the authors' bios: https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/306%20-%20Green%20jobs%20opportunities%20for%20women%20in%20the%20Latin%20America%20and%20the%20Caribbean%20region/[Bios.docx](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/306%20-%20Green%20jobs%20opportunities%20for%20women%20in%20the%20Latin%20America%20and%20the%20Caribbean%20region/Bios.docx?d=we67f77a5a4a4459b90d294439ef443c0&csf=1&web=1&e=WXlwSQ)?d=we67f77a5a4a4459b90d294439ef443c0&csf=1&web=1&e=WXlwSQ

**Comment by g4brielvs** [comment]
@samsonlee530 @Juliavieiradeandradedias Thanks! The story is now published at https://datapartnership.org/updates/green-jobs-for-women-and-diverse-groups-help-promote-equality-and-climate-resilience/

**Comment by samsonlee530** [comment]
@g4brielvs  Thank you so much for publishing the story! The final version has a footnote (in the second paragraph under the "challenge" section). Would you mind adding it back to the blog post? Thanks again.

**Comment by samsonlee530** [comment]
@g4brielvs Claudia has added the footnote to the story.
