### ISSUE TITLE
347 - The Transition to Telework in Latin America and the Caribbean

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#159]
Disseminate outcomes of proposal [The Transition to Telework in Latin America and the Caribbean](https://github.com/datapartnership/operations/issues/57)

**Comment by SahitiSarva** [comment]
The outputs of this project are [in this SharePoint](https://worldbankgroup.sharepoint.com.mcas.ms/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Yvwh8r&cid=fccdf23e%2D94d5%2D48bf%2Db75d%2D0af291138bde&FolderCTID=0x012000CFAB9FF0F938A64EBB297E7E16BDFCFD&id=%2Fteams%2FDevelopmentDataPartnershipCommunity%2DWBGroup%2FShared%20Documents%2FOutputs%2F347%20%2D%20The%20Transition%20to%20Telework%20in%20Latin%20America%20and%20the%20Caribbean&viewid=80cdadb3%2D8bb3%2D47ae%2D8b18%2Dc1dd89c373c5)

The team shared this report that can be published

**Comment by SahitiSarva** [comment]
https://publications.iadb.org/en/transition-telework-latin-america-and-caribbean-key-findings-using-linkedin-data

**Comment by samsonlee530** [comment]
Please kindly review this [draft](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/347%20-%20The%20Transition%20to%20Telework%20in%20Latin%20America%20and%20the%20Caribbean/DRAFT%20Impact%20Story%20telework%20in%20LAC.docx?d=w5167bcaab8274ceba0b5d44ae88581a2&csf=1&web=1&e=MWSsZP)

**Comment by samsonlee530** [comment]
@claudiacalderon @g4brielvs @SahitiSarva Update: I sent a draft to the IDB team at the end of May. But we haven't heard back from them yet. So I just sent a follow up email to them.

**Comment by samsonlee530** [comment]
The team has revised the draft. Here's the final [version](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/347%20-%20The%20Transition%20to%20Telework%20in%20Latin%20America%20and%20the%20Caribbean/FINAL%20Impact%20Story%20telework%20in%20LAC.docx?d=w5bc86516b26343feaeb54a7cd0a2b93f&csf=1&web=1&e=zQv1Yo)

**Comment by samsonlee530** [comment]
And the [bios](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/347%20-%20The%20Transition%20to%20Telework%20in%20Latin%20America%20and%20the%20Caribbean/[bios_ingles_16june2023.docx](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/347%20-%20The%20Transition%20to%20Telework%20in%20Latin%20America%20and%20the%20Caribbean/bios_ingles_16june2023.docx?d=wc438f33085614ceca7000a5e089dbf7f&csf=1&web=1&e=SGgXpr)?d=wc438f33085614ceca7000a5e089dbf7f&csf=1&web=1&e=SGgXpr)

**Comment by samsonlee530** [comment]
https://github.com/datapartnership/datapartnership.github.io/pull/213

**Comment by g4brielvs** [comment]
> @g4brielvs @claudiacalderon I created a blog post for the first time. Not sure whether the pull request was correctly made: #213 I also added the bios to the "authors" folder

Thank you for working on this story and for being open to learning a new thing. I just updated the contributing guidelines with additional information. The only observation is that we should use the [feature branch workflow]([feature branch workflow](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fwww.atlassian.com.mcas.ms%2Fgit%2Ftutorials%2Fcomparing-workflows%2Ffeature-branch-workflow%3FMcasTsid%3D20893&McasCSRF=313a315cf2c888f447b0b0ab4d2dda48e89a950038e9fff3a13e73574fbded26)). Please see the PR above.

**Comment by samsonlee530** [comment]
https://datapartnership.org/updates/telework-adoption-in-lac/
