### ISSUE TITLE
81 - Africa Digital Transformation Flagship Report – Background Study on Telecom Market Characteristics, Regulation and Market Outcomes (Speed)

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#162]
Write a blog story about the Digital Africa report.

**Comment by SahitiSarva** [comment]
The team produced outputs using Ookla data and sent the preliminary draft of images to Ookla to review. Their report is due Mid-March. Need to follow up with the team around then

**Comment by SahitiSarva** [comment]
The output for this team is released - https://www.worldbank.org/en/region/afr/publication/digital-africa

**Comment by claudiacalderon** [comment]
@samsonlee530 The team used Ookla data, highlighted in Chapter 4.

**Comment by samsonlee530** [comment]
@claudiacalderon Please this draft for your review, thank you.
[DRAFT Impact Story_81.docx](https://github.com/datapartnership/datapartnership.github.io/files/11050948/DRAFT.Impact.Story_81.docx)

**Comment by claudiacalderon** [comment]
@samsonlee530 here are the [comments](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/81%20-%20Africa%20Digital%20Transformation/[DRAFT.Impact.Story_81.docx](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/81%20-%20Africa%20Digital%20Transformation/DRAFT.Impact.Story_81.docx?d=w1be48d9258e34a36b4204f2dfd06fe19&csf=1&web=1&e=iFrdFk)?d=w1be48d9258e34a36b4204f2dfd06fe19&csf=1&web=1&e=iFrdFk)

**Comment by samsonlee530** [comment]
@claudiacalderon Also can't open this link.

**Comment by claudiacalderon** [comment]
waiting for ookla to green light it and then we can publish it

**Comment by samsonlee530** [comment]
Update: Ookla has reviewed the document after Tania and Clara's edits. I just sent the file to Tania and Clara for their final review before it goes live. I also asked Clara to share her bio with us.

**Comment by samsonlee530** [comment]
Here's the finalized version that has been reviewed by Clara and Tania: [file](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7BB18C5988-0522-472F-B5A3-7F131D798EBA%7D&file=FINALIZED%20Impact%20Story_81.docx&action=default&mobileredirect=true)

And Clara's bio is [here](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/81%20-%20Africa%20Digital%20Transformation/Clara%20Stinshoff%20BIO.docx?d=w400497f720b04f8f88348da682a81fad&csf=1&web=1&e=4g90wg)

**Comment by g4brielvs** [comment]
@samsonlee530 @claudiacalderon Thank you so much! I'm on it.
