### ISSUE TITLE
Is El Salvador’s health care system ready for telemedicine?

### ISSUE THREAD

**Issue by claudiacalderon** [datapartnership/datapartnership.github.io#168]
https://blogs.worldbank.org/digital-development/el-salvadors-health-care-system-ready-telemedicine

**Comment by samsonlee530** [comment]
@claudiacalderon Please review this [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7BED9F79BF-07FD-4D3C-8FB8-70E793595ACF%7D&file=DRAFT%20Impact%20Story%20El%20Salvador.docx&action=default&mobileredirect=true)

**Comment by samsonlee530** [comment]
Update: The World Bank team has cleared the draft. I have sent it to Kathy from Ookla for her review.

**Comment by samsonlee530** [comment]
Here is the final [version](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/El%20Salvador%27s%20healthcare%20system/FINAL%20Impact%20Story%20El%20Salvador.docx?d=w32c1ab7416b245df89985c6b25c06513&csf=1&web=1&e=ElSH2C)
