### ISSUE TITLE
[208] Did internet speed impact exposure to COVID-19?

### ISSUE THREAD

**Issue by claudiacalderon** [datapartnership/datapartnership.github.io#169]
Summery of the Blog in Partnership Format: https://blogs.worldbank.org/digital-development/did-internet-speed-impact-exposure-covid-19

**Comment by claudiacalderon** [comment]
@samsonlee530, here are some[ comments.](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/208%20-%20Internet%20quality%20in%20Colombia%20and%20El%20Salvador/[DRAFT.Impact.Story_208.docx](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/208%20-%20Internet%20quality%20in%20Colombia%20and%20El%20Salvador/DRAFT.Impact.Story_208.docx?d=w46bca8a4cd814009aa67d3dbf582e3c1&csf=1&web=1&e=bZEPUK)?d=w46bca8a4cd814009aa67d3dbf582e3c1&csf=1&web=1&e=bZEPUK)

**Comment by samsonlee530** [comment]
@claudiacalderon  Unfortunately, I can't access the link.

**Comment by claudiacalderon** [comment]
waiting for ookla to green light it and then we can publish it

**Comment by claudiacalderon** [comment]
revised story [here](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B13E10F63-F35B-4D56-8415-7C6180C49785%7D&file=Impact.Story_208(edited).docx&action=default&mobileredirect=true)

**Comment by g4brielvs** [comment]
We've published this impact story as https://datapartnership.org/updates/covid19-internet-speed-impact.
