### ISSUE TITLE
Insights from Leveraging Big Data to Track the Impact of the COVID-19 Pandemic on Mobility in Buenos Aires

### ISSUE THREAD

**Issue by claudiacalderon** [datapartnership/datapartnership.github.io#170]
https://openknowledge.worldbank.org/server/api/core/bitstreams/f1d2fd58-a15b-4e2a-b80e-1dc088f2f97f/content

**Comment by claudiacalderon** [comment]
@SahitiSarva feel free to adjust as you know what proposal this is related. Creating an issue since I saw it online and I don't want to miss it.

**Comment by samsonlee530** [comment]
@claudiacalderon Please see this [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B710C7EF8-A207-4D42-997F-BB93BD2C4420%7D&file=DRAFT%20Impact%20Story%20Buenos%20Aires.docx&action=default&mobileredirect=true)

**Comment by samsonlee530** [comment]
Update: I have sent the draft to Aiga and Javier.
