### ISSUE TITLE
Breaking Barriers: Female Entrepreneurs Who Cross Over to Male Dominated Sectors

### ISSUE THREAD

**Issue by claudiacalderon** [datapartnership/datapartnership.github.io#171]
The World Bank Africa Gender Innovation Lab, the East Asia and Pacific Gender Innovation Lab, and the Latin America and the Caribbean Gender Innovation Lab analyzed Facebook’s Future of Business to offer insight into who are the women who break into male-dominated sectors across 

https://openknowledge.worldbank.org/server/api/core/bitstreams/7031b50b-f682-52f5-9a3a-24dc46c77942/content

**Comment by samsonlee530** [comment]
@claudiacalderon Please see this [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7BB5546D4F-FC8F-4BF7-899F-A43D96867E95%7D&file=Impact%20story_female%20entrepreneurs.docx&action=default&mobileredirect=true)

Thank you.

**Comment by samsonlee530** [comment]
The World Bank team is reviewing the second [draft](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/Breaking%20Barriers%20Female%20Entrepreneurs%20Who%20Cross%20Over%20to%20Male%20Dominated%20Sectors/2nd%20DRAFT%20Impact%20story_female%20entrepreneurs.docx?d=w6347d6ff96744721b01fcedcb5ee4747&csf=1&web=1&e=3ygDnr)

**Comment by samsonlee530** [comment]
@claudiacalderon @g4brielvs @SahitiSarva Update: After their second review, I revised the draft and sent a clean version to them before we publish it.

**Comment by samsonlee530** [comment]
@claudiacalderon @g4brielvs @SahitiSarva The World Bank team has cleared the final [version](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/Breaking%20Barriers%20Female%20Entrepreneurs%20Who%20Cross%20Over%20to%20Male%20Dominated%20Sectors/FINAL%20Impact%20story_female%20entrepreneurs.docx?d=w6347d6ff96744721b01fcedcb5ee4747&csf=1&web=1&e=94hdbP)

**Comment by claudiacalderon** [comment]
@samsonlee530 @g4brielvs are we ready to publish this one?
