### ISSUE TITLE
Brave New World of Mobility Data

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/datapartnership.github.io#177]
We propose a series to describe the opportunities and challenges in leveraging mobility data for global crisis.

**Comment by g4brielvs** [comment]
@samsonlee530 We would like to start a series about the opportunities and challenges in leveraging mobility data on global crisis. Would you be open to helping us with it?

**Comment by samsonlee530** [comment]
> @samsonlee530 We would like to start a series about the opportunities and challenges in leveraging mobility data to tackle global crisis. Would you be open to helping us with it?

Sure. Can I have more details please? What projects would you like to highlight?

**Comment by g4brielvs** [comment]
@jfulponi Could you please prepare a bibliography that we could suggest to staff new to mobility data and its applications and limitations?
