### ISSUE TITLE
221 - LinkedIn in LAC

### ISSUE THREAD

**Issue by samsonlee530** [datapartnership/datapartnership.github.io#183]
https://publications.iadb.org/en/linkedin-latin-america-and-caribbean-rapid-transformation-labor-market-due-pandemic

**Comment by SahitiSarva** [comment]
Connected to the proposal https://github.com/datapartnership/operations/issues/157

**Comment by samsonlee530** [comment]
Please review this [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B84C675E8-4A6D-450E-A993-A45504F68B0A%7D&file=DRAFT%20Impact%20Story%20LinkekIn%20in%20LAC.docx&action=default&mobileredirect=true&cid=b0a08328-9221-4d80-8427-acc5ab6f8e7c)

**Comment by g4brielvs** [comment]
@samsonlee530 @claudiacalderon @SahitiSarva Please let me know if we can move this story to **Ready to Publish**.

**Comment by samsonlee530** [comment]
@claudiacalderon Please let me know if you have any comments on the story, thanks.

**Comment by samsonlee530** [comment]
Update: Lorena has sent the draft to her team. Waiting for their comments.

**Comment by samsonlee530** [comment]
I have created a pull request.
