### ISSUE TITLE
168 - Maldives - Assessment of Digital Development

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#193]
Maldives Digital Transformation Ookla project. Outputs here - https://worldbankgroup.sharepoint.com.mcas.ms/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Yvwh8r&cid=fccdf23e%2D94d5%2D48bf%2Db75d%2D0af291138bde&FolderCTID=0x012000CFAB9FF0F938A64EBB297E7E16BDFCFD&id=%2Fteams%2FDevelopmentDataPartnershipCommunity%2DWBGroup%2FShared%20Documents%2FOutputs%2F168%20%2D%20Assessment%20of%20Digital%20Development&viewid=80cdadb3%2D8bb3%2D47ae%2D8b18%2Dc1dd89c373c5

**Comment by samsonlee530** [comment]
I have sent a draft to the project team.

**Comment by samsonlee530** [comment]
[draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/doc2.aspx?sourcedoc=%7B7E2D550A-A3D1-401D-A426-07C4A08E182D%7D&file=DRAFT%20Impact%20Story%20Maldives.docx&action=default&mobileredirect=true&CID=b99b41bb-8199-422a-1ec1-1ff84e4e6e3b)

**Comment by samsonlee530** [comment]
I have sent a follow up email to the project team as I haven't received their comments on the draft.

**Comment by samsonlee530** [comment]
The project team has left feedback on the draft. I will revise it.

**Comment by samsonlee530** [comment]
I have sent the draft to Kathy from Ookla.

**Comment by samsonlee530** [comment]
Both the project team and Ookla have approved the draft. I have created a pull request for publishing the story. Thanks.

**Comment by g4brielvs** [comment]
> Both the project team and Ookla have approved the draft. I have created a pull request for publishing the story. Thanks.

@samsonlee530 Thanks! For reference, #229 is the pull request.
