### ISSUE TITLE
377 - Analyzing digital skills gap in MENA countries to inform an upskilling initiative

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#205]
[Output folder where the team shared their draft report](https://worldbankgroup.sharepoint.com/:f:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/377%20-%20Analyzing%20digital%20skills%20gap%20in%20MENA%20countries%20to%20inform%20an%20upskilling%20initiative?csf=1&web=1&e=tqRdfg)

**Comment by samsonlee530** [comment]
Here is a [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B4D75EA09-BFB5-4C49-BAA3-6F6F17ADD6DB%7D&file=DRAFT%20377%20Impact%20story%20digital%20skill%20gap%20MENA.docx&action=default&mobileredirect=true)

**Comment by samsonlee530** [comment]
The draft is under review by Angela and her team.

**Comment by samsonlee530** [comment]
The project team has edited the draft. I have also revised it following their feedback. Here is an updated [version](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B4D75EA09-BFB5-4C49-BAA3-6F6F17ADD6DB%7D&file=DRAFT%20377%20Impact%20story%20digital%20skill%20gap%20MENA.docx&nav=eyJjIjo2NzgyNDYzMjh9&action=default&mobileredirect=true&CID=5cc46e59-041c-31cf-a9d3-2084f14a53a6)

**Comment by samsonlee530** [comment]
The final version is [here](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/doc2.aspx?sourcedoc=%7B4D75EA09-BFB5-4C49-BAA3-6F6F17ADD6DB%7D&file=DRAFT%20377%20Impact%20story%20digital%20skill%20gap%20MENA.docx&action=default&mobileredirect=true&CID=c618b8a5-b54c-c293-5200-c054b0b19177

**Comment by samsonlee530** [comment]
Please review this pull request: https://github.com/datapartnership/datapartnership.github.io/pull/244
