### ISSUE TITLE
[367] Human Capital for Inclusive Development in Argentina

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#212]
```[tasklist]
### Tasks
- [ ] https://github.com/datapartnership/operations/issues/269
```

**Comment by samsonlee530** [comment]
Here is a [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7BCD1FDE5C-676F-453A-9F71-DC13C739C88C%7D&file=DRAFT%20367%20Argentina.docx&nav=eyJjIjo1NTkzMjI1ODB9&action=default&mobileredirect=truel)

**Comment by samsonlee530** [comment]
I have sent it to the project team.

**Comment by samsonlee530** [comment]
The project team has reviewed the blog post. I have then sent it to Casey.

**Comment by samsonlee530** [comment]
Both the project team and LinkedIn have reviewed the blog post.
