### ISSUE TITLE
 Understanding cross-border trade dynamics in West Africa in the context of a border closure

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/datapartnership.github.io#215]
Write this [proposal's impact story](https://portal.datapartnership.org/submitproposal/220).

## Outputs

- https://www.worldbank.org/en/region/afr/publication/benin-country-economic-memorandum-accelerating-the-growth-momentum-and-creating-better-jobs

**Comment by g4brielvs** [comment]
@samsonlee530 @claudiacalderon Thank you for the [draft](https://mcas-proxyweb.mcas.ms/certificate-checker?login=false&originalUrl=https%3A%2F%2Fworldbankgroup.sharepoint.com.mcas.ms%2F%3Aw%3A%2Fr%2Fteams%2FDevelopmentDataPartnershipCommunity-WBGroup%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B43260993-6427-407C-A1EA-FDC3E0B62769%257D%26file%3DDRAFT%2520Impact%2520Story%2520Benin.docx%26action%3Ddefault%26mobileredirect%3Dtrue%26McasTsid%3D20893&McasCSRF=ae4d4bae2e5ea095c962af424b4b57b6bfa2e22e5531201c80d079b7f034e2f1).

**Comment by samsonlee530** [comment]
I have sent a follow up email to the project team today.

**Comment by samsonlee530** [comment]
Both Outlogic and the project team have approved the draft. I have uploaded the story to GitHub. https://github.com/datapartnership/datapartnership.github.io/pull/237
