### ISSUE TITLE
[324] Temperature and Well-being in Argentina

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/datapartnership.github.io#217]
This team has done some solid work using twitter data and the initial outputs can be found on [SharePoint](https://worldbankgroup.sharepoint.com.mcas.ms/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Yvwh8r&cid=fccdf23e%2D94d5%2D48bf%2Db75d%2D0af291138bde&FolderCTID=0x012000CFAB9FF0F938A64EBB297E7E16BDFCFD&id=%2Fteams%2FDevelopmentDataPartnershipCommunity%2DWBGroup%2FShared%20Documents%2FOutputs%2F324%20%2D%20Well%2Dbeing%20and%20temperature%20in%20Argentina&viewid=80cdadb3%2D8bb3%2D47ae%2D8b18%2Dc1dd89c373c5)

**Comment by claudiacalderon** [comment]
@SahitiSarva is there more info for this one?

**Comment by SahitiSarva** [comment]
Let me follow up with the team!

**Comment by SahitiSarva** [comment]
The team mentioned that they're working on a working paper for which they're using new NLP techniques. We should wait on this blog piece @samsonlee530

**Comment by samsonlee530** [comment]
@SahitiSarva Thanks for the update.

**Comment by samsonlee530** [comment]
Here is the final version of the blog post: https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7BA44EA8FF-A54D-4582-9B60-C9D81EEB1CB6%7D&file=BlogDDPHeatTweets_FINAL.docx&action=default&mobileredirect=true
