### ISSUE TITLE
[388] Mapping mobility in secondary cities in Argentina

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/datapartnership.github.io#240]
Write the impact story of [Mapping mobility in secondary cities in Argentina](https://portal.datapartnership.org/readableproposal/388). See [outputs](https://worldbankgroup.sharepoint.com/:f:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Outputs/388%20-%20Mapping%20mobility%20in%20secondary%20cities%20in%20Argentina?csf=1&web=1&e=ebuRTw).

**Comment by samsonlee530** [comment]
Here is a [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7BFA9E3207-727C-46C1-88F2-5D3B0CF40ECF%7D&file=Draft%20388%20Impact%20Story%20Urban%20Mobility%20in%20Argentina.docx&action=default&mobileredirect=true)

**Comment by samsonlee530** [comment]
https://datapartnership.org/updates/traffic-congestion-argentina/
