### ISSUE TITLE
[476] Comparing the performance of GPS data VS. surveys in estimating mobility indicators in Lima

### ISSUE THREAD

**Issue by samsonlee530** [datapartnership/datapartnership.github.io#242]
https://blogs.worldbank.org/transport/improving-lives-lima-one-intersection-time

**Comment by samsonlee530** [comment]
Here is a [draft](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B63C13B19-4928-4B6C-B2FE-CF5767BCE11E%7D&file=DRAFT%20476%20Impact%20Story%20Lima.docx&action=default&mobileredirect=true)

**Comment by samsonlee530** [comment]
I have sent the draft to the project team.

**Comment by samsonlee530** [comment]
The project team has reviewed the draft. Claudia has sent it to Waze.

**Comment by samsonlee530** [comment]
I have sent a follow up email to Andrew from Google.

**Comment by samsonlee530** [comment]
All the data partners have reviewed the draft. Here is the final [version](https://worldbankgroup.sharepoint.com.mcas.ms/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B4237FB70-9A3A-4B55-BA75-16923333B9A9%7D&file=FINAL%20476%20Impact%20Story%20Lima.docx&action=default&mobileredirect=true&CT=1706599092049&OR=ItemsView)

**Comment by samsonlee530** [comment]
Here is a pull request to publish the story: https://github.com/datapartnership/datapartnership.github.io/pull/256

**Comment by g4brielvs** [comment]
@samsonlee530 Thanks! You may select the PR under "Development" and by doing so, the issue will be closed automagically. 


<img width="330" alt="Screenshot 2024-01-31 at 10 57 03 AM" src="https://github.com/datapartnership/datapartnership.github.io/assets/4053416/26f9cbb8-2c31-45f5-af72-19afd8ab2de1">
