### ISSUE TITLE
[522] Changing Labor Markets in EBRD Economies

### ISSUE THREAD

**Issue by samsonlee530** [datapartnership/datapartnership.github.io#260]
I have drafted a blog [post](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B3B526A2A-9304-4FBB-BDAB-90DF029514AE%7D&file=DRAFT%20522%20-%20Implications%20of%20the%20Green%20Transition%20for%20the%20Labor%20Market.docx&action=default&mobileredirect=true)

**Comment by g4brielvs** [comment]
Closing in favor of https://github.com/datapartnership/datapartnership.github.io/issues/266.
