### ISSUE TITLE
[522] - Changing Labour Markets In EBRD Economies

### ISSUE THREAD

**Issue by samsonlee530** [datapartnership/datapartnership.github.io#266]
Publication: https://www.ebrd.com/news/publications/transition-report/transition-report-202324.html
Proposal: https://portal.datapartnership.org/readableproposal/522

**Comment by samsonlee530** [comment]
Final version of the [story](https://worldbankgroup.sharepoint.com.mcas.ms/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/_layouts/15/Doc.aspx?sourcedoc=%7B3E6D21F5-3FDF-46FD-B5B9-9AC584CA2EE0%7D&file=FINAL%20522%20-%20Implications%20of%20the%20Green%20Transition%20for%20the%20Labor%20Market%20(1)%20(1).docx&action=default&mobileredirect=true)

**Comment by samsonlee530** [comment]
@g4brielvs @claudiacalderon I wanted to link this to the proposal. But I can't seem to find it here: https://github.com/orgs/datapartnership/projects/9/views/19

**Comment by g4brielvs** [comment]
> @g4brielvs @claudiacalderon I wanted to link this to the proposal. But I can't seem to find it here: https://github.com/orgs/datapartnership/projects/9/views/19

@samsonlee530 Thanks! Here's the [proposal issue](https://github.com/orgs/datapartnership/projects/9/views/19?pane=issue&itemId=45672103) (it didn't show up because the tag was missing). Also, I'm closing https://github.com/datapartnership/datapartnership.github.io/issues/260 to avoid duplication and updating the [link](https://github.com/orgs/datapartnership/projects/9/views/19?pane=issue&itemId=45672103).

**Comment by samsonlee530** [comment]
> > @g4brielvs @claudiacalderon I wanted to link this to the proposal. But I can't seem to find it here: https://github.com/orgs/datapartnership/projects/9/views/19
> 
> @samsonlee530 Thanks! Here's the [proposal issue](https://github.com/orgs/datapartnership/projects/9/views/19?pane=issue&itemId=45672103) (it didn't show up because the tag was missing). Also, I'm closing #260 to avoid duplication and updating the [link](https://github.com/orgs/datapartnership/projects/9/views/19?pane=issue&itemId=45672103).

Thanks!
