### ISSUE TITLE
Big Data Spatial Joins

### ISSUE THREAD

**Issue by MrMaksimize** [datapartnership/datapartnership.github.io#30]
Gabriel: Dask
Maksim: Spark
Aivin: Analysis?

**Comment by g4brielvs** [comment]
See [Visualizing Millions of Waze Traffic Alerts with BigQuery, H3 and Dask](https://datapartnership.org/updates/visualizing-millions-of-waze-traffic-alerts-with-google-bigquery-and-dask/).
