### ISSUE TITLE
[255] Digitalization and Resilience to COVID-19 Shocks: Evidence from Sub-Saharan Africa

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/datapartnership.github.io#94]
Habemus a new story! Publish story of [Digitalization and Resilience to COVID-19 Shocks: Evidence from Sub-Saharan Africa](https://portal.datapartnership.org/readableproposal/255).

- [x] Finalize text on Word document (include link here) (@lamyakejji )
- [x] Submit text for Ookla's approval (@claudiacalderon)
- [x] Create post in Markdown
- [x] #95.

**Comment by samsonlee530** [comment]
https://datapartnership.org/updates/imf-digitalization-in-sub-saharan-africa/
